-- TCM_CCTV_RAW: 10분 주기 RAW 데이터
CREATE TABLE IF NOT EXISTS TCM_CCTV_RAW (
    SEQ           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CORP_CD       VARCHAR(10) NOT NULL DEFAULT '25001',
    CONNECT_INFO  VARCHAR(200) NOT NULL,
    INSERT_DT     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MALE_IN       INT NOT NULL DEFAULT 0,
    MALE_OUT      INT NOT NULL DEFAULT 0,
    FEMALE_IN     INT NOT NULL DEFAULT 0,
    FEMALE_OUT    INT NOT NULL DEFAULT 0,
    TOTAL_IN      INT NOT NULL DEFAULT 0,
    TOTAL_OUT     INT NOT NULL DEFAULT 0,
    INDEX idx_insert_dt (INSERT_DT),
    INDEX idx_connect (CONNECT_INFO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TCM_CCTV_STATISTICS: 정시(매시 00분) 통계 데이터
CREATE TABLE IF NOT EXISTS TCM_CCTV_STATISTICS (
    SEQ           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CORP_CD       VARCHAR(10) NOT NULL DEFAULT '25001',
    CONNECT_INFO  VARCHAR(200) NOT NULL,
    INSERT_DT     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MALE_IN       INT NOT NULL DEFAULT 0,
    MALE_OUT      INT NOT NULL DEFAULT 0,
    FEMALE_IN     INT NOT NULL DEFAULT 0,
    FEMALE_OUT    INT NOT NULL DEFAULT 0,
    TOTAL_IN      INT NOT NULL DEFAULT 0,
    TOTAL_OUT     INT NOT NULL DEFAULT 0,
    INDEX idx_insert_dt (INSERT_DT),
    INDEX idx_connect (CONNECT_INFO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
